<a href="https://colab.research.google.com/github/EthanW67/Machine-Learning-Research/blob/main/Machine-Learning-Research/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Research NoteBook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.3.0+cu121


Creating Tensors --> torch.tensors()


In [ ]:
# SCALAR TENSOR
# Scalar tensor have zero dimensions
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
# Getting tensor back as a python int
scaler.item()

7

In [ ]:
# Vector Tensor
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
# Matrix
Matrix = torch.tensor([[7,8],
                     [9, 10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
Matrix[1]

tensor([ 9, 10])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]
                       ])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR = torch.tensor([[[1,2,3,4],
                       [4,5,6,3],
                       [7,8,9,3],
                      [10,11,12,14]]
                       ])
TENSOR

tensor([[[ 1,  2,  3,  4],
         [ 4,  5,  6,  3],
         [ 7,  8,  9,  3],
         [10, 11, 12, 14]]])

In [ ]:
TENSOR.shape

torch.Size([1, 4, 4])

Command mm - converts comments into headers

Create Random Tensors


In [ ]:
# Random Tensors
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2606, 0.1638, 0.8413, 0.6409],
        [0.0694, 0.9281, 0.3715, 0.7214],
        [0.0532, 0.5379, 0.9110, 0.4426]])

In [ ]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size = (224, 224, 3)) # height, weight, color (rbg)


Tensor of Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size= (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Creating a range of tensors and tensor-like

range = torch.arange

like = torch.zeros_like

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
torch.arange(start= 1, end= 100, step=5)

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
        91, 96])

In [ ]:
# Creating tensor like
# Uses the format of a tensor and replaces all the elements in it with zero
ten_zeros = torch.zeros_like(input= one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes
3 big errors

  Tensors not right datetype

  Tensors not right shape
  
  Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor ([3.0, 6.0, 9.0],
                                dtype = None, # what datetype is the tensor (float32, float16)
                                device = None, # What device is yoru tensor on
                                requires_grad= False) # whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
# Convert to Float 32 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting Information from Tensors (Tensors Attributies)

1. Incorrect Datatype: tensor.dtype
2. Incorrect Shape: tensor.shape or tensor.size()
3. Incorrect Device: tensor.device


In [ ]:
# Create a tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3605, 0.8526, 0.2882, 0.7799],
        [0.0412, 0.4679, 0.7893, 0.7472],
        [0.0538, 0.6768, 0.6466, 0.2493]])

In [ ]:
# Details about the Tensor
print(random_tensor)
print(f"Datatype: {random_tensor.dtype}")
print(f"Shape: {random_tensor.shape}")
print(f"Device: {random_tensor.device}")

tensor([[0.3605, 0.8526, 0.2882, 0.7799],
        [0.0412, 0.4679, 0.7893, 0.7472],
        [0.0538, 0.6768, 0.6466, 0.2493]])
Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


In [ ]:
# Float 16 Tensor Information
float_16_tensor = random_tensor.type(torch.float16)

print(float_16_tensor)
print(f"Datatype: {float_16_tensor.dtype}")
print(f"Shape: {float_16_tensor.shape}")
print(f"Device: {float_16_tensor.device}")

tensor([[0.3606, 0.8525, 0.2883, 0.7798],
        [0.0412, 0.4678, 0.7896, 0.7471],
        [0.0538, 0.6768, 0.6465, 0.2493]], dtype=torch.float16)
Datatype: torch.float16
Shape: torch.Size([3, 4])
Device: cpu


### Tensor Operations
Addition

Subtraction

Multiplication

Division

Matrix Multiplication


In [ ]:
# Create Tensor
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [ ]:
# Add Tensor
tensor_1 = tensor + 10
torch.add(tensor, 4)

tensor([5, 6, 7])

In [ ]:
# Multiply
tensor_1 * 10
torch.mul(tensor,15)

tensor([15, 30, 45])

In [ ]:
# Subtract
torch.sub(tensor,10)
tensor - 11

tensor([-10,  -9,  -8])

### Matrix Multiplication
Two ways of multiplication
1. Regular
2. Matrix multiplication (dot product):
torch.matmul()

Two Rules:
1. Inner Dimensions Must Match For Shape
* (3,2) @ (3,2) won't work
* (3,2) @ (2,3) works
2. The resulting Matrix has the Shape of the Outer Elements
* (3,2) @ (2,3) --> (3,3)



In [ ]:
# Element Wise Mult
print(tensor, "*", tensor)
print(tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [ ]:
# Matrix Muliplcation
%%time
torch.matmul(tensor, tensor)

CPU times: user 971 µs, sys: 798 µs, total: 1.77 ms
Wall time: 8.61 ms


tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += (tensor[i] * tensor[i])
print(value)

tensor(14)
CPU times: user 1.65 ms, sys: 0 ns, total: 1.65 ms
Wall time: 1.72 ms


Shape Errors
1. Transpose: Switches the axes or dimensions of a given tensor

In [ ]:
# Shape for Matrix Muliplicaiton
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A, tensor_B)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

Transpose --> tensor.T

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Tensor Aggregation (min, max, mean, sum,

*   Mean --> Need to be float15 or float 32 type
*   List item

etc)

In [ ]:
# Create a tensor
tensor = torch.arange(0,100, 10)
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(tensor), tensor.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(tensor), tensor.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(tensor.type(torch.float32))

tensor(45.)

In [ ]:
torch.sum(tensor), tensor.sum()

(tensor(450), tensor(450))

### Finding the Positiona Min and Max
1. torch.argmin()
2. torch.argmax()

In [ ]:
# Returns the index where the min value is --> 0
torch.argmin(tensor)

tensor(0)

In [ ]:
tensor_1 = torch.rand(1,4)
tensor_1

tensor([[0.6991, 0.3755, 0.8811, 0.7067]])

In [ ]:
tensor_1.argmin()

tensor(1)

In [ ]:
# Returns the index where the max value is
tensor.argmax()

tensor(9)

### Reshaping, Stacking, Squeezing, and Unsqueezing Tensors
* Reshaping
* View
* Stacking
* Squeeze
* Unsqueeze

In [ ]:
#Create Tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

Reshaping

In [ ]:
# Adding Extra dimensions
# Element amount must Match i.e. We have 9 elements so we have to have either 9 tensors or
# 1 tensor with 9 elements
# Reshape must be compatible with the original size
x_reshaped = x.reshape((1,9))
x_reshaped, x_reshaped.shape
# i.e 10 elements you can have (2,5) since 2 * 5 = 10

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

View
* Changing z changes x (since they have the same memory

In [ ]:
# Changing the view
#They share the same memory
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

Stacking
* Good for combining tensors of the same size and dim

In [ ]:
# Stack Tensors on top of each other
x_stacked = torch.stack((x,x,x,x), dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stack = torch.rand(3)
y_stack = torch.rand(3)
z_stack = torch.rand(3)
xyz_stack = torch.stack((x_stack, y_stack, z_stack))
xyz_stack

tensor([[0.8816, 0.5392, 0.9759],
        [0.5082, 0.9873, 0.5193],
        [0.7633, 0.6014, 0.8619]])

Squeeze and Unsqueeze
* Squeeze: Removes all single dimensions form a target tensor. i.e. [1,1,9] would be [9]
* Unsqueeze: Add a single dimension to a target tensor at a specific dim (dim0, dim1, dim2, dim(n))

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

Permute

In [ ]:
# torch.permute: rearranges the dimensions of a target tensor in a specific order
x_original = torch.rand(size = (224,224,3)) # height, weight, colour_channel

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2,1,0) # shifted the dim from 0 to 2, 1 to 1, 2 to 0
print(x_original.shape)
print(x_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


## Indexing: Selecting data from Tensors

Indexing with Pytrch is similar to indexing with NumPy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Index on dim = 0
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Index on dim = 1 (Middle Bracket)
x[0, 0]

tensor([1, 2, 3])

In [ ]:
# Index on dim = 2
x[0,0,2]

tensor(3)

In [ ]:
# : is used to get "all" of a target dimension
x[:,1,:]

tensor([[4, 5, 6]])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index to find 9
x[0,2,2]

tensor(9)

In [ ]:
# Index to find (3,6,9)
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch Tensors & Numpy
* NumPy --> PyTorch: torch.from_numpy(ndarray)
*When converting Num to Torch: Torch datatype becomes 64 instead of 32
* PyTorch --> NumPy: torch.Tensor.numpy()
* Don't share memory i.e they will not effecte each other when the values change

In [ ]:
# NumPy to Tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Changing the Value of the array
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Changing the value of Tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Pytorch Reproducibility (taking the random out of random)
* Start with random num --> tensor opertations --> update random number to try and make better representatiosn of the data --> repeat
* Reduce randomness in nn and pytorch is the comcept of (random seed)
* Random Seed --> flavours the randomness


In [ ]:
import torch
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1315, 0.9611, 0.1717, 0.6607],
        [0.6831, 0.4565, 0.0057, 0.8351],
        [0.4439, 0.3203, 0.3787, 0.9988]])
tensor([[0.4600, 0.5744, 0.6325, 0.3269],
        [0.8434, 0.3948, 0.4875, 0.9135],
        [0.8485, 0.6798, 0.4600, 0.1254]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Random but Reproducible Tensors
import torch
# Set the Random Seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Works for only one blop of code so use random seed for every tensor
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running Tensors & PyTorch onjects on the GPUs
* Runtime --> Change Runtime Type --> Select GPU --> Rerun everything


In [ ]:
# Check for GPU acces with Pytorch
import torch
torch.cuda.is_available()


True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device
# Allows you to use Cuda if available or cpu instead if not available

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

## Putting Tensors and Models on the GPU

In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])
# Tensor is default on CPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move Tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Move Tensors back to CPU
* NumPy cannot be used if on GPU


In [ ]:
# Tensor on GPU cannot transform to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# GPU Tensor --> Numpy : first set it to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises